name: Run Azure Activity PowerShell Script

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-powershell-script:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Ensure Logs directory exists
        run: New-Item -ItemType Directory -Path Logs -Force
        shell: pwsh

      - name: Execute PowerShell script and save logs
        run: |
          $timestamp = Get-Date -Format 'yyyy-MM-dd_HH-mm'
          $logFile = "./Logs/Logs_$timestamp.txt"
          Write-Output "Starting Azure Activity Script Execution..." | Out-File -FilePath $logFile -Append
          .\HelloWorld.ps1 | Out-File -FilePath $logFile -Append
        shell: pwsh

      - name: Commit and push logs
        env:
          SCRIPT_AUTOMATION: ${{ secrets.SCRIPT_AUTOMATION }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add Logs/*
          git commit -m "Add log file for run at $timestamp"
          git push https://x-access-token:${{ secrets.SCRIPT_AUTOMATION }}@github.com/shivanshu08/Automated-Script-Execution.git
        shell: pwsh
