name: Run Azure Activity PowerShell Script

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-powershell-script:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Execute PowerShell script and save logs
        run: |
          New-Item -ItemType Directory -Path Logs -Force
          $timestamp = Get-Date -Format 'yyyy-MM-dd_HH-mm'
          $logFile = "./Logs/Logs_$timestamp.txt"
          Write-Output "Starting Azure Activity Script Execution..." | Out-File -FilePath $logFile -Append
          .\HelloWorld.ps1 | Out-File -FilePath $logFile -Append
        shell: pwsh
