name: Run Azure Activity PowerShell Script

# Schedule to run every 1 hour
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:  

jobs:
  run-powershell-script:
    runs-on: windows-latest
    steps:
      # Checkout the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Run the PowerShell script and save logs
      - name: Execute PowerShell script and save logs
        run: |
          # Define log file name with date and time
          $logFile = "Logs/Log_$(Get-Date -Format 'dd-MM-yyyy_HH-mm').log"
          # Display a message to indicate start
          Write-Output "Starting Azure Activity Script Execution..." | Out-File -FilePath $logFile -Append
          # Execute the script and save the output to the log file
          .\HelloWorld.ps1 | Out-File -FilePath $logFile -Append
        shell: pwsh
