name: Run Azure Activity PowerShell Script
 
# Schedule to run every 10 minutes
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allows manual triggering of the workflow
 
jobs:
  run-powershell-script:
    runs-on: windows-latest
    steps:
      # Checkout the repository
      - name: Check out repository
        uses: actions/checkout@v3
 
      # Run the PowerShell script
      - name: Execute PowerShell script
        run: |
          # Display a message to indicate start
          Write-Output "Starting Azure Activity Script Execution..."
          # Execute the script in the repository
          .\HelloWorld.ps1
        shell: pwsh
